### ISSUE TITLE
Setup Deliver configurarion from 'fastlane init' command fails

### ISSUE THREAD

**Issue by maurobender** [KrauseFx/fastlane#639]
When running __'fastlane init'__ with no previous Deliver configuration created the init process fails with the next error:

```
[10:14:20]: Loading up 'deliver', this might take a few seconds
[10:14:25]: Error occurred with the setup program! Reverting changes now!
[10:14:25]: Deleting the 'fastlane' folder
/Users/maurobender/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.29.2/lib/fastlane/setup.rb:108:in `ask_to_enable_other_tools': uninitialized constant Deliver::DeliverfileCreator (NameError)
	from /Users/maurobender/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.29.2/lib/fastlane/setup.rb:25:in `run'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.29.2/bin/fastlane:49:in `block (2 levels) in run'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.29.2/bin/fastlane:127:in `run'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.29.2/bin/fastlane:133:in `<top (required)>'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/maurobender/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Running __'deliver init'__ first seems to solve the problem because there's not need to create the Deliver configuration from the __'fastlane init'__ command.

Running __fastlane 1.29.2__.

**Comment by KrauseFx** [comment]
I assume you installed the `deliver` beta? If so, `fastlane` was not yet updated to use the new beta.

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.
Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

**Comment by maurobender** [comment]
I've tried it and now is working ok with __fastlane 1.30.2__. The weird thing is that I haven't installed `deliever`beta, I've just installed fastlane and deliver was installed as a dependecy, maybe the beta was set as a dependency for that version. Anyway, with the update to the version __1.30.2__ of the gem everything seems to be working just fine.  

Thanks!

**Comment by KrauseFx** [comment]
:+1:

**Comment by cytryn** [comment]
I am having the same issue... just followed the guide with a skeleton project. Any Ideas why the error occurred?

This message shows up right after showing the summary:

```
[22:06:49]: Error occurred with the setup program! Reverting changes now!
[22:06:49]: Moving './fastlane/screenshots' to 'screenshots'
[22:06:49]: Deleting the 'fastlane' folder
/Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:31:in `generate_deliver_file': undefined method `latest_version' for "app":String (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:14:in `create_based_on_identifier'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.2.0/lib/deliver/setup.rb:5:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.0/lib/fastlane/setup.rb:110:in `ask_to_enable_other_tools'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.0/lib/fastlane/setup.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.0/bin/fastlane:48:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.0/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.0/bin/fastlane:142:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
@crylico Sorry about that. That's because you have the Apple TV app enabled. The latest `spaceship` release should fix that :+1:

**Comment by crylico** [comment]
@KrauseFx @cytryn got mentioned by mistake - just want to make sure you both get necessary notifications 😊

**Comment by KrauseFx** [comment]
Haha, you're the best @crylico :+1:

**Comment by MickeyHub** [comment]
Maybe the same Issue, and what important info I got from console is : 
> please submit an issue on GitHub and attach the following number to it: 'f96d0750202c9258ab7aacc2dae16629'
