### ISSUE TITLE
Error after updating to 0.12.3

### ISSUE THREAD

**Issue by pbendersky** [KrauseFx/fastlane#216]
I was using 0.10.0 without issues. Today, I updated to 0.12.3, and I with this Fastfile:

```
fastlane_version "0.12.3"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods

    # increment_build_number

    # ipa

    xctool
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end
end
```
I get the following error when running `fastlane test`:
```
INFO [2015-04-20 14:35:44.19]: -------------------------------------------------
INFO [2015-04-20 14:35:44.19]: --- Step: Verifying required fastlane version ---
INFO [2015-04-20 14:35:44.19]: -------------------------------------------------
INFO [2015-04-20 14:35:44.19]: fastlane version valid
INFO [2015-04-20 14:35:44.19]: ------------------------------
INFO [2015-04-20 14:35:44.19]: --- Step: default_platform ---
INFO [2015-04-20 14:35:44.19]: ------------------------------
INFO [2015-04-20 14:35:44.20]: Driving the lane 'ios test'
INFO [2015-04-20 14:35:44.20]: --------------------
INFO [2015-04-20 14:35:44.20]: --- Step: xctool ---
INFO [2015-04-20 14:35:44.20]: --------------------
INFO [2015-04-20 14:35:44.20]: Variable Dump:
INFO [2015-04-20 14:35:44.20]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
FATAL [2015-04-20 14:35:44.20]: undefined method `join' for #<FastlaneCore::Configuration:0x007fc246fb2628>
FATAL [2015-04-20 14:35:45.63]: fastlane finished with errors
/Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/actions/xctool.rb:9:in `run': undefined method `join' for #<FastlaneCore::Configuration:0x007fc246fb2628> (NoMethodError)
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):32:in `block (3 levels) in parse'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/runner.rb:31:in `call'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/runner.rb:31:in `block in execute'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/runner.rb:24:in `chdir'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/runner.rb:24:in `execute'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:178:in `call'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/command.rb:153:in `run'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/runner.rb:68:in `run!'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/commander-4.3.2/lib/commander/delegates.rb:15:in `run!'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/bin/fastlane:118:in `run'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/fastlane-0.12.3/bin/fastlane:124:in `<top (required)>'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `load'
	from /Users/Pablo/.rbenv/versions/2.0.0-p247/bin/fastlane:23:in `<main>'
```

Just in case I deleted the entire `fastlane` folder and recreated it using `fastlane init` but the result is the same.

Any hint?

**Comment by KrauseFx** [comment]
Thanks for reporting, I'll push a fix in a minute!

**Comment by pbendersky** [comment]
Update: changing the Fastfile to `xctool(Array.new)` or `xctool([])` serves as a workaround, but I think there's a bug in the `xctool` action.

**Comment by KrauseFx** [comment]
Yes, thanks, I just pushed a fix: https://github.com/KrauseFx/fastlane/commit/81dfa2c33cca5bd3cb3360e5d35b3cabab2fd3ba

A new release will be available later today :+1: 

In the mean time, do it like you posted above

**Comment by pbendersky** [comment]
Thank you @KrauseFx!

**Comment by KrauseFx** [comment]
Thank you for reporting @pbendersky. Sorry for the troubles with the new version. There were some major changes under the hood.
